# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2022 Abdellatif El Khlifi <abdellatif.elkhlifi@arm.com>
#

obj-y += arm-ffa-uclass.o core.o
obj-$(CONFIG_ARM_FFA_EFI_RUNTIME_MODE) += efi_ffa_runtime_data_mgr.o
obj-$(CONFIG_SANDBOX_FFA) += sandbox.o
